name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v2
      - name: ğŸ“¦ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: ğŸ“¦ Install dependencies for backend
        run: cd backend && yarn install --frozen-lockfile
      - name: âœ… Test backend
        run: cd backend && yarn test
      - name: ğŸ¨ Prettier check backend
        run: cd backend && yarn format
      - name: ğŸ“¦ Install dependencies for frontend
        run: cd frontend && yarn install --frozen-lockfile
      - name: âœ… Test frontend
        run: cd frontend && yarn test
      - name: ğŸ¨ Prettier check frontend
        run: cd frontend && yarn format
      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: ğŸ—ï¸ Build and run Docker services
        run: docker-compose up --build -d
